### ISSUE TITLE
Finish User Data type

### ISSUE THREAD

**Issue by imkiva** [LemonHX/LemonVM#20]
As is described in #13

**Comment by imkiva** [comment]
Here is the context of why we need a **User Data Type**:

![image](https://user-images.githubusercontent.com/9902643/80978987-57883800-8e59-11ea-83ad-b0d6804f7eea.png)

![image](https://user-images.githubusercontent.com/9902643/80979070-78508d80-8e59-11ea-91d5-2f2e00bd834a.png)

**Comment by LemonHX** [comment]
@imkiva @Phosphorus15 and I are planning to working on it
