### ISSUE TITLE
When Using LLDB, Async Codes Will Allways Gives Me Memory Errors

### ISSUE THREAD

**Issue by LemonHX** [LemonHX/LemonVM#25]
such as 
- Stop reason: Exception 0xc0000005 encountered at address 0x7ff76ab5e78e: Access violation reading location 0xffffffffffffffff (but i have never used 0xffffffffffffffff )
- OOM
- etc

**Comment by SchrodingerZhu** [comment]
Linux cannot even load:
```
===== Prototype =====
< arg_types: [], ret_types: [] >
( params: 0, is_vargs?: false, rets:0 )
{ number of labels: 1 }
sub functions: 0
instructions:
  0x0000:  ["0x02000100"]


===== testing FFI =====
before execute []
[1]    1730117 segmentation fault (core dumped)  ./LemonVM
```

**Comment by SchrodingerZhu** [comment]
[valgrind.log](https://github.com/LemonHX/LemonVM/files/4596758/valgrind.log)

**Comment by SchrodingerZhu** [comment]
[valgrind2.log](https://github.com/LemonHX/LemonVM/files/4596784/valgrind2.log)
