### ISSUE TITLE
Rebase away those dlls and libs in master or just move them to test

### ISSUE THREAD

**Issue by SchrodingerZhu** [LemonHX/LemonVM#28]
It is not tidy to keep the temp files within the root of the master.
You can just write a `build.rs` to create them in test.

**Comment by imkiva** [comment]
Yes, maybe we need a test module

**Comment by SchrodingerZhu** [comment]
@LemonHX I see the dlls in the commit history, would you mind just rebase them out of the history.

```
git rebase <TARGET> -i
```
then use
```
edit
```
to modify those commits.

**Comment by LemonHX** [comment]
I think you can do it
