### ISSUE TITLE
Finish C ABI Function call

### ISSUE THREAD

**Issue by LemonHX** [LemonHX/LemonVM#4]

**Comment by LemonHX** [comment]
@Phosphorus15 过来干活就完了~

**Comment by Phosphorus15** [comment]
issue tracking branch https://github.com/LemonHX/LemonVM/tree/foreign

**Comment by LemonHX** [comment]
@Phosphorus15 you should not create a new type of instruction, and 0x26 is already in used

**Comment by LemonHX** [comment]
@Phosphorus15 I will rename this branch FFI
